### ISSUE TITLE
Bug: Error updating IDN Zonefile

### ISSUE THREAD

**Issue by mschaller** [rembik/dehydrated-hetzner-hook#11]
The hook works very well for my domains, except that one with an international domain name like küche.de --> xn--kche-0ra.de (not my domain, just an example)

here the output:

```
 + Logging in on Hetzner Robot with account "xxx"
 + Landing on page https://accounts.hetzner.com/account/masterdata with status code 200 and cookie <RequestsCookieJar[<Cookie PHPSESSID=8eafe364f5d8be8206aab888fbc926d3 for accounts.hetzner.com/>]>
 + Landing on page https://robot.your-server.de/ with status code 200 and cookie <RequestsCookieJar[<Cookie robot=ad1b92b65855c7c397b7d14913cffe5c for robot.your-server.de/>]>
 + Checking domain _acme-challenge.xn--kche-0ra.de for valid CNAME entry
 + Domain _acme-challenge.xn--kche-0ra.de has no CNAME entry
 + Challenge dns-01: _acme-challenge.xn--kche-0ra.de => qK28F1b6CfshSz9v2MiwnYmVvLvyC4bpEUxBKc2dqeQ as TXT record
 + Requesting list of zone IDs
 + Responsed 5 zone IDs
Traceback (most recent call last):
  File "/etc/dehydrated/hooks/hetzner/hook.py", line 390, in <module>
    main(sys.argv[1:])
  File "/etc/dehydrated/hooks/hetzner/hook.py", line 386, in main
    ops[argv[0]](argv[1:])
  File "/etc/dehydrated/hooks/hetzner/hook.py", line 337, in create_all_txt_records
    create_txt_record(args[i:i+X], session)
  File "/etc/dehydrated/hooks/hetzner/hook.py", line 288, in create_txt_record
    zone_id = _get_zone_id(domain, session)
  File "/etc/dehydrated/hooks/hetzner/hook.py", line 169, in _get_zone_id
    return zone_ids[tld]
KeyError: 'xn--kche-0ra.de'
```

my python-skills are very basic, so I have no idea why it runs into an error. If I remove the domain from domains.txt the script will pass all other domains.

it runs in an alpine docker-container with python 3.6.4.

**Comment by rembik** [comment]
#6
