### ISSUE TITLE
Support for Hetzner KonsoleH

### ISSUE THREAD

**Issue by nix-nutz** [rembik/dehydrated-hetzner-hook#14]
Hi, 
i did setup a fresh Debian stretch and followed the instructions in the README file. (BTW: debian users need also to run "pip3 install wheel" before installing requirements, otherwise installation of "future" will fail). I did setup config files accordingly, and did run "dehydrated --register --accept-terms".

When i run dehydrated -c the first time, i get this output:
 root@mail /opt # dehydrated -c
# INFO: Using main config file /etc/dehydrated/config
 + [Errno 2] No such file or directory: '/etc/dehydrated/hooks/hetzner/accounts/K0XXXXXX.json' - config for account "K0XXXXXX"! Try default hook config instead
 + [Errno 2] No such file or directory: '/etc/dehydrated/hooks/hetzner/accounts/K0XXXXXX.json' - config for account "K0XXXXXX"! Try default hook config instead
 + Hetzner Robot hook executing: startup_hook
 + Creating chain cache directory /etc/dehydrated/chains
Processing example.net with alternative names: *.example.net
 + Creating new directory /etc/dehydrated/certs/example.net ...
 + [Errno 2] No such file or directory: '/etc/dehydrated/hooks/hetzner/accounts/K0K0XXXXXX.json' - config for account "K0K0XXXXXX"! Try default hook config instead
 + [Errno 2] No such file or directory: '/etc/dehydrated/hooks/hetzner/accounts/K0XXXXXX.json' - config for account "K0XXXXXX"! Try default hook config instead
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 2 authorizations URLs from the CA
 + Handling authorization for example.net
 + Handling authorization for example.net
 + 2 pending challenge(s)
 + Deploying challenge tokens...
 + [Errno 2] No such file or directory: '/etc/dehydrated/hooks/hetzner/accounts/K0XXXXXX.json' - config for account "K0XXXXXX"! Try default hook config instead
 + Hetzner Robot hook executing: deploy_challenge
 + Logging in on Hetzner Robot with account "K0XXXXXX"
 + Landing on page https://accounts.hetzner.com/account/masterdata with status code 200 and cookie <RequestsCookieJar[<Cookie PHPSESSID=b6f9404sd2345a153c04e650c0f for accounts.hetzner.com/>]>
 + Landing on page https://robot.your-server.de/ with status code 200 and cookie <RequestsCookieJar[<Cookie robot=89a5df34df252b5760eb6f9be7c for robot.your-server.de/>]>
 + Checking domain _acme-challenge.example.net for valid CNAME entry
 + Domain _acme-challenge.example.net has no CNAME entry
 + Challenge dns-01: _acme-challenge.example.net => NUVGDDdN9b-Tx1OT3NLaH9vdaa2_5Rj-aH9KsKuXNYA as TXT record
 + Requesting list of zone IDs
 + Updating list of zone IDs
 + Updated & responsed 0 zone IDs
Traceback (most recent call last):
  File "/etc/dehydrated/hooks/hetzner/hook.py", line 390, in <module>
    main(sys.argv[1:])
  File "/etc/dehydrated/hooks/hetzner/hook.py", line 386, in main
    ops[argv[0]](argv[1:])
  File "/etc/dehydrated/hooks/hetzner/hook.py", line 337, in create_all_txt_records
    create_txt_record(args[i:i+X], session)
  File "/etc/dehydrated/hooks/hetzner/hook.py", line 288, in create_txt_record
    zone_id = _get_zone_id(domain, session)
  File "/etc/dehydrated/hooks/hetzner/hook.py", line 169, in _get_zone_id
    return zone_ids[tld]
KeyError: 'example.net'

My python is poor, i try'd to investigate the code, seems like the function _update_zone_id does return 0 zone_ids

Nix-Nutz

**Comment by nix-nutz** [comment]
With the help of rembik i found the problem causing this error. When using Hetzner, the domain needs to be added to Hetzner Robot, Hetzner KonsoleH is not supported.

I currently transfer the domain to Hetzner Robot, i will let you now if this solves the issue.

**Comment by nix-nutz** [comment]
After moving the domain from Hetzner KonsoleH to Hetzner Robot the hook worked like a charm, rembik thank you for helping!
