### ISSUE TITLE
[SOLVED] zone_ids dict seems off

### ISSUE THREAD

**Issue by bolausson** [rembik/dehydrated-hetzner-hook#15]
Hej,

I just tried your hook but it failed on me.

When it creates the "zone_ids" dict something seems to be off:

```
root@nvr:~# dehydrated -c
# INFO: Using main config file /etc/dehydrated/config
# !! WARNING !! Extra configuration directory /etc/dehydrated/conf.d exists, but no configuration found in it.
Processing nvr.local.mydomain.de
 + Signing domains...
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for nvr.local.mydomain.de...
 + Hetzner Robot hook executing: deploy_challenge
 + Logging in on Hetzner Robot with account "myusername"
 + Landing on page https://accounts.hetzner.com/account/masterdata with status code 200 and cookie <RequestsCookieJar[<Cookie PHPSESSID=894a334e6g050a009a9cb279e1a1e59d for accounts.hetzner.com/>]>
 + Landing on page https://robot.your-server.de/ with status code 200 and cookie <RequestsCookieJar[<Cookie robot=19474b2556hc881b4bb1325451953b44 for robot.your-server.de/>]>
 + Checking domain _acme-challenge.nvr.local.mydomain.de for CNAME entry
   SOA de => The DNS query name does not exist: de.local.mydomain.de.
   NS de => The DNS query name does not exist: de.local.mydomain.de.
   DNS de => IPv4 ['8.8.8.8', '8.8.4.4']
   CNAME _acme-challenge.nvr.local.mydomain.de => The DNS response does not contain an answer to the question: _acme-challenge.nvr.local.mydomain.de. IN CNAME
 + CNAME _acme-challenge.nvr.local.mydomain.de => False
 + Challenge dns-01: _acme-challenge.nvr.local.mydomain.de => T9Aly9aX_6ybJ61VlzAnuh5Zbz4tdO_YQz-Gu27n7Ow as TXT record
 + Requesting list of zone IDs
 + tld: de
 + Responsed 3 zone IDs
 + zone_ids: {'mydomain2.de': 298431, 'mydomain1.de': 165441, 'mydomain.de': 165406}
Traceback (most recent call last):
  File "/var/lib/dehydrated/hooks/hetzner/hook.py", line 427, in <module>
    main(sys.argv[1:])
  File "/var/lib/dehydrated/hooks/hetzner/hook.py", line 423, in main
    ops[argv[0]](argv[1:])
  File "/var/lib/dehydrated/hooks/hetzner/hook.py", line 376, in create_all_txt_records
    create_txt_record(args[i:i+X], session)
  File "/var/lib/dehydrated/hooks/hetzner/hook.py", line 328, in create_txt_record
    zone_id = _get_zone_id(domain, session)
  File "/var/lib/dehydrated/hooks/hetzner/hook.py", line 200, in _get_zone_id
    return zone_ids[tld]
KeyError: 'de'
```

Cheers,
Bjoern

**Comment by rembik** [comment]
Ahoi Bjoern,

you installed the pip package tld version >7.x. 

In tld versions >=8 the output of get_tld() has changed to only the top level domain. What makes sense, but nevertheless we need the whole first level domain as we get in versions <8. So remove tld and install the requiered version 7.6 or edit the code to use the newer get_fld() function.

**Comment by bolausson** [comment]
Spot on 👍 

I reverted to 7.x and not it works like a charm.

Thanks!

Cheers,
Bjoern
