### ISSUE TITLE
login to hetzner robot fails recently

### ISSUE THREAD

**Issue by level420** [rembik/dehydrated-hetzner-hook#16]
I know that this hook is deprecated, but I'm still using this hook.

I'm getting the the following error with the latest code freshly pulled from github:

```
# INFO: Using main config file /etc/dehydrated/config
# INFO: Using additional config file /etc/dehydrated/conf.d/local.sh
 + Hetzner hook executing startup_hook...
Processing mydomain.tld with alternative names: *.mydomain.tld
 + Checking domain name(s) of existing cert... unchanged.
 + Checking expire date of existing cert...
 + Valid till Apr  3 01:42:25 2019 GMT (Less than 30 days). Renewing!
 + Signing domains...
 + Generating signing request...
 + Requesting new certificate order from CA...
 + Received 2 authorizations URLs from the CA
 + Handling authorization for mydomain.tld
 + Handling authorization for mydomain.tld
 + 2 pending challenge(s)
 + Deploying challenge tokens...
 + Hetzner hook executing deploy_challenge...
Traceback (most recent call last):
  File "/etc/dehydrated/hooks/hetzner/hook.py", line 821, in <module>
    main(sys.argv[1:])
  File "/etc/dehydrated/hooks/hetzner/hook.py", line 818, in main
    ops[argv[0]](argv[1:])
  File "/etc/dehydrated/hooks/hetzner/hook.py", line 767, in deploy_challenge
    provider = Provider()
  File "/etc/dehydrated/hooks/hetzner/hook.py", line 129, in __init__
    assert self.username is not None
AssertionError
```

This may be due to changes in the robot frontend recently.

Would be great to get a hint on how I could adapt the hook to the new frontend.
Thank you in advance!

**Comment by tombreit** [comment]
The nameing of environment variables to authenticate your Hetzner user seem to have changed (https://github.com/rembik/dehydrated-hetzner-hook/commit/f8dd044f6139e0627e32c11c82000d6131440884): 
```bash
# Hetzner account: by default Hetzner Robot (robot) or Hetzner konsoleH (konsoleh)
#export HETZNER_AUTH_ACCOUNT='robot'
export HETZNER_AUTH_USERNAME='<username>'
export HETZNER_AUTH_PASSWORD='<password>'
```

**Comment by rembik** [comment]
@level42: Can we close this issue?

**Comment by level420** [comment]
Oh! sorry! forgot about that issue.

Yes. closing this, because as @tombreit said it worked with the new environment variables and meanwhile I've managed to use https://github.com/AnalogJ/lexicon where it worked out of the box.

Thank you for the reminder.
