### ISSUE TITLE
Login to Hetzner robot fails after Change USER Login

### ISSUE THREAD

**Issue by hermannbrauer** [rembik/dehydrated-hetzner-hook#17]
Since the change of the authentication at Hetzner from user name to e-mail address, the login does not work anymore

Hetzner => Enable CNAME lookup (see --linked parameter)
Starting new HTTPS connection (1): accounts.hetzner.com
Traceback (most recent call last):
  File "/etc/dehydrated/hooks/hetzner/hook.py", line 821, in <module>
    main(sys.argv[1:])
  File "/etc/dehydrated/hooks/hetzner/hook.py", line 818, in main
    ops[argv[0]](argv[1:])
  File "/etc/dehydrated/hooks/hetzner/hook.py", line 773, in deploy_challenge
    provider.authenticate()
  File "/etc/dehydrated/hooks/hetzner/hook.py", line 138, in authenticate
    with self._session(self.domain, get_zone=False):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/etc/dehydrated/hooks/hetzner/hook.py", line 629, in _session
    self.session = self._auth_session(self.username, self.password)
  File "/etc/dehydrated/hooks/hetzner/hook.py", line 654, in _auth_session
    response = session.request('GET', endpoint + api['GET'].get('url', '/'))
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python2.7/dist-packages/urllib3/util/retry.py", line 242, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'

**Comment by hermannbrauer** [comment]
login on customer number converted, then it goes again!
